version: '3'

services:
  web:
    build: .
    volumes:
      - static:/code/static
      - .:/code
  
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    depends_on:
      - web

volumes:
  .:
  static:
