# Generated by Django 3.2 on 2021-04-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_client_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='api.Supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='articles',
            field=models.ManyToManyField(blank=True, to='api.Article'),
        ),
    ]
