# Generated by Django 3.2 on 2021-04-10 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_order_served_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlequantity',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.supplier'),
            preserve_default=False,
        ),
    ]
