# Generated by Django 3.2 on 2021-04-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
