# Generated by Django 3.2 on 2021-04-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210407_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='OrderArticles', through='api.ArticleQuantity', to='api.Article'),
        ),
    ]
